---
title: "SDM Tutorial - Jade"
output: html_document
date: "2023-08-08"
---

```{r eval=FALSE}
devtools::install_github("BigelowLab/maxnet", force = TRUE)
```

```{r}
suppressPackageStartupMessages(
  {library(maxnet)
  library(dplyr)
  library(maxnet)
  library(sf)
  library(stars)
  library(geodata)
  library(dismo)
  library(lubridate)
  library(sdmpredictors)
  library(zoon)
  library(ggplot2)
  library(cmocean)
  library(janitor)
  library(DT)
})
```



## Data set up

```{r}
# Presence data
library(readr)
Occurrence <- read_csv("~/Downloads/e1dfe463-237b-41ce-8103-adbf286404b1/Occurrence.csv")
summary(Occurrence)

o_cols <- c('decimallongitude','decimallatitude','date_year','coordinateuncertaintyinmeters','bathymetry','sst','sss')

o_data <- data.frame(Occurrence)[o_cols]
good <- which(o_data$coordinateuncertaintyinmeters < 200)
presence <- o_data[good,]
summary(presence)

presence.points <- sf::st_as_sf(presence, coords = c("decimallongitude", "decimallatitude"), crs = 4326)
```

```{r}
# Absence data

library(readr)
absence <- read_csv("~/ohw23_proj_marinesdms/data/raw-bio/pts_absence.csv")
colnames(absence) <- c("decimallongitude","decimallatitude")
absence <- na.omit(absence)

absence.points <- sf::st_as_sf(absence, coords = c("decimallongitude", "decimallatitude"), crs = 4326)
```



# Setting up environmental datasets and combine with presence/absence data

```{r}
# Loading datasets

datasets <- list_datasets(terrestrial = FALSE, marine = TRUE)
#View(datasets)
layers <- list_layers(datasets)
#View(layers)
```

```{r}
# Environmental data layers to use + cropping to the study area

layercodes <- c("BO_bathymean","BO_sstmean","BO2_salinitymean_ss")
env <- load_layers(layercodes)
env <- stack(env)

lons <- c(30, 90) 
lats <- c(-10,30)

ext <- raster::extent(lons[1], lons[2], lats[1], lats[2])
extent_polygon <- as(ext, "SpatialPolygons") %>% st_as_sf()
sf::st_crs(extent_polygon) <- 4326 
studyarea <- raster::crop(env, extent(extent_polygon))
plot(studyarea)
```

```{r}
# Combining environmental data to the presence/absence data

env.stars <- stars::st_as_stars(env) # convert to stars object
env.stars <- split(env.stars)

presence_env <- stars::st_extract(env.stars, sf::st_coordinates(presence.points)) |>
  dplyr::as_tibble() |>
  na.omit()

absence_env <- stars::st_extract(env.stars, sf::st_coordinates(absence.points)) |>
  dplyr::as_tibble() |>
  na.omit()
```



## Running model

```{r}
# Final data preparation

presence_env <- na.omit(presence_env); absence_env <- na.omit(absence_env) # remove NA values

finaldata <- c(rep(1, nrow(presence_env)), rep(0, nrow(absence_env))) # create values of 1 for presence data and 0 for absence data

sdm.model <- maxnet::maxnet(finaldata, rbind(presence_env, absence_env))
```

### Model metrics

```{r}
responses <- plot(sdm.model, type = "cloglog")
```

## Predicting

```{r}
bb <- sf::st_bbox(extent_polygon)
clamp <- TRUE       # see ?predict.maxnet for details
type <- "cloglog"
predicted <- predict(sdm.model, env.stars %>% 
                       sf::st_crop(bb), clamp = clamp, type = type)
predicted
```



## Visualization

```{r}
# ggplot - with occurrence data points

ggplot() +
  geom_stars(data = predicted) +
  scale_fill_cmocean(name = "ice", direction = -1, guide = guide_colorbar(barwidth = 1, barheight = 10, ticks = FALSE, nbin = 1000, frame.colour = "black"), limits = c(0, 1)) +
  theme_linedraw() +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(title = "Green sea turtle species distribution model",
       x = "Longitude",
       y = "Latitude",
       fill = "Probability",
       shape = "Species (presence)",
       subtitle = "Environmental predictors: mean SS temp, mean SS salinity, mean bathymetry, mean pH, mean DO") +
  geom_point(presence.points, mapping = aes(geometry = geometry), stat = "sf_coordinates", alpha = 0.1, color = "purple") +
  #scale_x_continuous(breaks = seq(40, 70, 10), limits = c(42, 70))+
  scale_y_continuous(breaks = seq(0, 30, 10))

ggsave("SDM_green_w points.pdf", height = 6, width = 8.5)

  #+
#  geom_point(abs.points, mapping = aes(geometry = geometry), stat = "sf_coordinates", alpha = 0.7, color = "gray")
```

```{r}
# ggplot - without occurrence data points

ggplot() +
  geom_stars(data = predicted) +
  scale_fill_cmocean(name = "ice", direction = -1, guide = guide_colorbar(barwidth = 1, barheight = 10, ticks = FALSE, nbin = 1000, frame.colour = "black"), limits = c(0, 1)) +
  theme_linedraw() +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(title = "Green sea turtle species distribution model",
       x = "Longitude",
       y = "Latitude",
       fill = "Probability",
       shape = "Species (presence)",
       subtitle = "Environmental predictors: mean SS temp, mean SS salinity, mean bathymetry, mean pH, mean DO") +
  #geom_point(occ.points, mapping = aes(shape = common.name, geometry = geometry), stat = "sf_coordinates", alpha = 0.3, color = "purple") +
  #scale_x_continuous(breaks = seq(40, 70, 10), limits = c(42, 70))+
  scale_y_continuous(breaks = seq(0, 30, 10))

ggsave("SDM_green.pdf", height = 6, width = 8.5)
```

```{r}
# base R

plot(predicted, reset = F, main = "Green sea turtle SDM") # predicted model
plot(presence.points, col = "cyan", add = TRUE, cex = 0.6, pch = 20) # occurrence points
plot(st_geometry(absence.points), add = T, cex = 0.6, col = "green", pch = 20, alpha = 0.2) # absence points
# legend(x = "topleft", legend = c("presence", "absence"), col = c("cyan","green"))
```