---
title: "SDM Roadmap"
---

This section (Background) discusses the steps of the Species Distribution Model (SDM) Workflow and shows some different approaches that you might take.

## SDM Workflow

Creating a Species Distribution Model (SDM) has general steps: 1) plan, 2) data preparation, 3) model fitting, 4) assessment and 5) predictions. These are the same for all SDMs independent of the particular algorithm used. 

In this tutorial, we discuss these steps in the context of marine SDMs using the example of the sea turtles in the Arabian Sea. In the "SDM Steps" section, we show the specific approaches that we use in the sea turtle SDM tutorial. This is a tutorial to get you more comfortable with the steps. They actual sea turtle model we produce is a "toy" example.

1. Specify the region

   -- shows how to create a bounding box for the region and some base maps
   
2. Obtain presence Data

   -- shows how to obtain sea turtle presence data from OBIS via `robis` 
   
3. Create Absence (also called background) Points

   -- discusses three methods to create random background points within a area of interest 
   
4. Extract environmental variables

   -- shows how to obtain environmental predictors of interest using `sdmpredictors`
   
4. Models

   -- discusses different SDM modeling options and discusses the maxent model that we use in this tutorial
   
5. Data Visualizations

## References

* The zoon project has a [nice summary](https://zoonproject.github.io/zoontutorials/articles/Introduction.html) of the steps to preparing a SDM.