---
title: "Occurrence map"
output: html_document
date: "2023-08-09"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(maxnet)
  library(dplyr)
  library(maxnet)
  library(sf)
  library(stars)
  library(geodata)
  library(dismo)
  library(lubridate)
  library(sdmpredictors)
})
```

Following Ben's tutorial https://github.com/BigelowLab/maxnet/wiki/stars

```{r}
occ.og <- read.csv("/home/jovyan/R/ohw23_proj_marinesdms/data/raw-bio/green_turtles.csv")

occ.sub <- subset(occ.og, longitude < 95 & longitude > 51 & latitude > -0.7 & latitude < 25.6)

# lat -0.7-25.6, lon 51-95

occ <- occ.sub[,c(5,2,3,7,8)]
```

```{r}
occ <- sf::st_as_sf(occ, coords = c("longitude", "latitude"), crs = 4326)
occ

occ$date_min <- lubridate::ymd(occ$date_min)
occ$date_max <- lubridate::ymd(occ$date_max)
```

```{r}
path <- tempdir()
recent <- geodata::worldclim_global(var="bio", res=10, path = path) |>
  stars::st_as_stars() |>
  split()
names(recent) <- sprintf("bio%0.2i", seq_len(length(names(recent))))
```

```{r}
clim <- geodata::cmip6_world(model = "CNRM-CM6-1", 
                              ssp = "585", 
                              res = 10, 
                              time = "2021-2040",
                              var = "bioc",
                              path = path) |>
  stars::st_as_stars(ignore_file = TRUE) |>
  split()
```

```{r}
env_obs <- stars::st_extract(recent, sf::st_coordinates(occ)) |>
  dplyr::as_tibble()
env_obs
```

```{r}
poly <- occ |>                                # start with obs
  sf::st_combine() |>                         # combine into a single multipoint
  sf::st_convex_hull() |>                     # find convex hull
  sf::st_transform(crs = sf::st_crs(5880)) |> # make planar
  #sf::st_buffer(dist = 200000) |>             # buffer by 200000m
  sf::st_transform(crs = sf::st_crs(4326))    # make spherical
```

```{r}
# N <- 1200
# back <- sf::st_sample(poly, N)
# 
# env_back <- stars::st_extract(recent, sf::st_coordinates(back)) |>
#   dplyr::as_tibble() |>
#   na.omit()
# env_back
```

```{r}
col <- sf.colors(categorical = TRUE)
bb <- sf::st_bbox(poly)
plot(recent[1], 
     main = "", axes = TRUE, key.pos = NULL, reset = FALSE)
maps::map('world', add = TRUE, lwd = 2)
plot(sf::st_geometry(occ), col = col[4], pch = 16, add = TRUE, cex = 0.8)
#plot(sf::st_geometry(poly), add = TRUE, border = col[5], lwd = 2)
#plot(back, add = TRUE, col = col[8], pch = ".")
```

SDM predictor variables

```{r}
datasets <- list_datasets(terrestrial = FALSE, marine = TRUE)
    View(datasets)
    layers <- list_layers(datasets)
    View(layers)
```

