{
  "hash": "65521530c3ca8bb74120197fa5baf80c",
  "result": {
    "markdown": "---\ntitle: \"Exploring OBIS sea turtle observations\"\noutput:\n  md_document:\n    variant: markdown_github\ndate: \"2023-08-10\"\n---\n\n\nIn this section, we will explore [Loggerhead sea turtle (*Caretta caretta*)](https://www.iucnredlist.org/species/3897/119333622) data from 2000 until present from the [Ocean Biodiversity Information System (OBIS)](https://obis.org/). We will use the `robis` package to search the OBIS library and download relevant data.  We will then check for quality control flags and remove problematic observations from the data (i.e., sea turtle observations on land).\n  \n# Loading libraries\n\n::: {.cell}\n\n```{.r .cell-code}\n#Dealing with spatial data\nlibrary(sf)\n#Getting base maps\nlibrary(rnaturalearth)\n#Access to OBIS\nlibrary(robis)\n#Data manipulation and visualisation\nlibrary(tidyverse)\nlibrary(janitor)\n```\n:::\n\n\n# Create a bounding box\nWe will use a bounding box for the region of our interest (Arabian Sea and the Bay of Bengal) to extract *C. caretta* data relevant to our study area.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\n#We create a bounding box using minimum and maximum coordinate pairs\nextent_polygon <- st_bbox(c(xmin = 41.875, xmax = 65.125, \n                            ymax = -0.125, ymin = 32.125), \n                          #Assign reference system\n                          crs = st_crs(4326)) %>% \n  #Turn into sf object\n  st_as_sfc()\n\n#Extract polygon geometry \npol_geometry <- st_as_text(extent_polygon[[1]])\n```\n:::\n\n  \n<<<<<<< HEAD\n# Get observations\n=======\n# Get Observations\n>>>>>>> e1113d9383b2e57473ce9195a510bd71774ecfda\nWe will use the `robis` package to find observations of Loggerhead sea turtles (*C. caretta*) published in OBIS.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Search OBIS for loggerhead observations from 2000\ncaretta_obs <- occurrence(\"Caretta caretta\", \n                          startdate = as.Date(\"2000-01-01\"),\n                          #Apply spatial constraint\n                          geometry = pol_geometry,\n                          #Include absence records if available\n                          absence = \"include\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nRetrieved 5000 records of approximately 5269 (94%)\nRetrieved 5269 records of\napproximately 5269 (100%)\n```\n:::\n\n```{.r .cell-code}\n#Check structure of results\nglimpse(caretta_obs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 5,269\nColumns: 103\n$ associatedReferences          <chr> \"[{\\\"crossref\\\":{\\\"citeinfo\\\":{\\\"origin\\…\n$ basisOfRecord                 <chr> \"MachineObservation\", \"MachineObservatio…\n$ bibliographicCitation         <chr> \"[{\\\"crossref\\\":{\\\"citeinfo\\\":{\\\"origin\\…\n$ catalogNumber                 <chr> \"1014_8853\", \"1014_9766\", \"1014_8861\", \"…\n$ collectionCode                <chr> \"1014\", \"1014\", \"1014\", \"1014\", \"1014\", …\n$ coordinatePrecision           <chr> \"9.99999999999999955e-07\", \"9.9999999999…\n$ coordinateUncertaintyInMeters <chr> \"0.11\", \"0.11\", \"0.11\", \"0.11\", \"0.11\", …\n$ datasetID                     <chr> \"1014\", \"1014\", \"1014\", \"1014\", \"1014\", …\n$ datasetName                   <chr> \"IFREMER/Kélonia satellite tracked late …\n$ dateIdentified                <chr> \"2012-03-30T08:55:10\", \"2011-04-12T19:12…\n$ decimalLatitude               <dbl> 9.14804, 6.40193, 9.21307, 15.39172, 15.…\n$ decimalLongitude              <dbl> 50.69448, 59.87883, 50.82211, 55.71303, …\n$ eventDate                     <chr> \"2012-03-30T08:55:10\", \"2011-04-12T19:12…\n$ eventTime                     <chr> \"05:55:10Z\", \"15:12:41Z\", \"23:43:31Z\", \"…\n$ family                        <chr> \"Cheloniidae\", \"Cheloniidae\", \"Cheloniid…\n$ footprintWKT                  <chr> \"POINT(50.69448 9.14804)\", \"POINT(59.878…\n$ genus                         <chr> \"Caretta\", \"Caretta\", \"Caretta\", \"Carett…\n$ geodeticDatum                 <chr> \"EPSG:4326 WGS84\", \"EPSG:4326 WGS84\", \"E…\n$ georeferencedDate             <chr> \"2012-03-30T08:55:10\", \"2011-04-12T19:12…\n$ identificationRemarks         <chr> \"Identification Type:Telemetry\", \"Identi…\n$ individualCount               <chr> \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", …\n$ institutionCode               <chr> \"IFREMER and Kélonia\", \"IFREMER and Kélo…\n$ kingdom                       <chr> \"Animalia\", \"Animalia\", \"Animalia\", \"Ani…\n$ license                       <chr> \"http://creativecommons.org/licenses/by-…\n$ lifeStage                     <chr> \"Juvenile\", \"Juvenile\", \"Juvenile\", \"Juv…\n$ modified                      <chr> \"2013-10-25 13:35:20\", \"2013-10-25 13:35…\n$ nomenclaturalCode             <chr> \"WoRMS LSID\", \"WoRMS LSID\", \"WoRMS LSID\"…\n$ occurrenceID                  <chr> \"1014_8853\", \"1014_9766\", \"1014_8861\", \"…\n$ occurrenceRemarks             <chr> \"Telemetry\", \"Telemetry\", \"Telemetry\", \"…\n$ occurrenceStatus              <chr> \"present\", \"present\", \"present\", \"presen…\n$ order                         <chr> \"Testudines\", \"Testudines\", \"Testudines\"…\n$ organismID                    <chr> \"57684\", \"66818\", \"57684\", \"66839\", \"668…\n$ organismRemarks               <chr> \"Tagged animal. organismID may refer to …\n$ ownerInstitutionCode          <chr> \"IFREMER and Kélonia\", \"IFREMER and Kélo…\n$ phylum                        <chr> \"Chordata\", \"Chordata\", \"Chordata\", \"Cho…\n$ recordNumber                  <chr> \"1014_8853\", \"1014_9766\", \"1014_8861\", \"…\n$ scientificName                <chr> \"Caretta caretta\", \"Caretta caretta\", \"C…\n$ scientificNameAuthorship      <chr> \"(Linnaeus, 1758)\", \"(Linnaeus, 1758)\", …\n$ scientificNameID              <chr> \"urn:lsid:marinespecies.org:taxname:1372…\n$ specificEpithet               <chr> \"caretta\", \"caretta\", \"caretta\", \"carett…\n$ taxonRank                     <chr> \"Species\", \"Species\", \"Species\", \"Specie…\n$ taxonRemarks                  <chr> \"Taxon recorded as \\\"Caretta caretta\\\" b…\n$ taxonomicStatus               <chr> \"valid\", \"valid\", \"valid\", \"valid\", \"val…\n$ type                          <chr> \"Event\", \"Event\", \"Event\", \"Event\", \"Eve…\n$ verbatimEventDate             <chr> \"2012-03-30 08:55:10\", \"2011-04-12 19:12…\n$ vernacularName                <chr> \"Loggerhead Sea Turtle\", \"Loggerhead Sea…\n$ waterBody                     <chr> \"Reunion Island,Oman,South-Africa\", \"Reu…\n$ id                            <chr> \"000341f8-f206-4120-bc73-432a0c729d7a\", …\n$ dataset_id                    <chr> \"7687b242-05b7-48d7-a316-ba6dc34e72b5\", …\n$ node_id                       <chr> \"573654c1-4ce7-4ea2-b2f1-e4d42f8f9c31\", …\n$ date_start                    <dbl> 1.333066e+12, 1.302566e+12, 1.333152e+12…\n$ date_mid                      <dbl> 1.333066e+12, 1.302566e+12, 1.333152e+12…\n$ date_end                      <dbl> 1.333066e+12, 1.302566e+12, 1.333152e+12…\n$ date_year                     <int> 2012, 2011, 2012, 2011, 2011, 2011, 2011…\n$ dropped                       <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…\n$ absence                       <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…\n$ marine                        <lgl> TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…\n$ subphylum                     <chr> \"Vertebrata\", \"Vertebrata\", \"Vertebrata\"…\n$ infraphylum                   <chr> \"Gnathostomata\", \"Gnathostomata\", \"Gnath…\n$ megaclass                     <chr> \"Tetrapoda\", \"Tetrapoda\", \"Tetrapoda\", \"…\n$ superclass                    <chr> \"Reptilia\", \"Reptilia\", \"Reptilia\", \"Rep…\n$ suborder                      <chr> \"Cryptodira\", \"Cryptodira\", \"Cryptodira\"…\n$ superfamily                   <chr> \"Chelonioidea\", \"Chelonioidea\", \"Cheloni…\n$ species                       <chr> \"Caretta caretta\", \"Caretta caretta\", \"C…\n$ kingdomid                     <int> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…\n$ phylumid                      <int> 1821, 1821, 1821, 1821, 1821, 1821, 1821…\n$ subphylumid                   <int> 146419, 146419, 146419, 146419, 146419, …\n$ infraphylumid                 <int> 1828, 1828, 1828, 1828, 1828, 1828, 1828…\n$ megaclassid                   <int> 1831, 1831, 1831, 1831, 1831, 1831, 1831…\n$ superclassid                  <int> 1838, 1838, 1838, 1838, 1838, 1838, 1838…\n$ orderid                       <int> 2689, 2689, 2689, 2689, 2689, 2689, 2689…\n$ suborderid                    <int> 148741, 148741, 148741, 148741, 148741, …\n$ superfamilyid                 <int> 987094, 987094, 987094, 987094, 987094, …\n$ familyid                      <int> 136999, 136999, 136999, 136999, 136999, …\n$ genusid                       <int> 137066, 137066, 137066, 137066, 137066, …\n$ speciesid                     <int> 137205, 137205, 137205, 137205, 137205, …\n$ aphiaID                       <int> 137205, 137205, 137205, 137205, 137205, …\n$ originalScientificName        <chr> \"Caretta caretta\", \"Caretta caretta\", \"C…\n$ category                      <chr> \"VU\", \"VU\", \"VU\", \"VU\", \"VU\", \"VU\", \"VU\"…\n$ flags                         <chr> \"NO_DEPTH\", \"NO_DEPTH\", \"NO_DEPTH\", \"NO_…\n$ bathymetry                    <int> 35, 3051, 136, 2784, 2453, 2736, 2880, 2…\n$ shoredistance                 <int> 4680, 899682, 12208, 193567, 143853, 100…\n$ sst                           <dbl> 26.21, 28.67, 26.21, 27.00, 26.92, 26.92…\n$ sss                           <dbl> 35.63, 35.74, 35.65, 36.09, 36.09, 36.10…\n$ dynamicProperties             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ sex                           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ continent                     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ country                       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ day                           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ georeferenceRemarks           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ locality                      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ maximumDepthInMeters          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ maximumElevationInMeters      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ minimumDepthInMeters          <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ minimumElevationInMeters      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ month                         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ recordedBy                    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ references                    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ samplingProtocol              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ year                          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ depth                         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ superdomain                   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ superdomainid                 <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n```\n:::\n:::\n\n  \n## Explore OBIS results\nOur search produced 5269 results for the area of our interest. However, before we continue to use this data as input for our species distribution models, we must clean it first to ensure we have a good quality dataset.  \n  \nIn this section, we will explore the results of our OBIS search so we can design a data cleaning workflow. We will check the content of some of the columns in our data frame.  \n\nYou may want to refer to the [OBIS manual](https://manual.obis.org/darwin_core.html) and the OBIS webpage about [Data Access](https://obis.org/data/access/).\n  \n\n::: {.cell}\n\n```{.r .cell-code}\n#Checking values in basis of record column\ncaretta_obs %>% \n  distinct(basisOfRecord)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 1\n  basisOfRecord     \n  <chr>             \n1 MachineObservation\n2 Occurrence        \n```\n:::\n:::\n\n \nIn this context, `MachineObservation` refers to records obtained with satellite tags. While `Occurrence` refers to records obtained by human observers on the field. These two datasets cannot be treated in the same way as `MachineObservation` records are not independent as they record the movements of a single individual.  \n    \nWe can also check whether or not absence data is available for the loggerhead se a turtles in our area of interest.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\ncaretta_obs %>% \n  distinct(absence)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  absence\n  <lgl>  \n1 FALSE  \n```\n:::\n:::\n\n  \nWe only have presence data available, which is an important factor to consider when designing our species distribution model workflow.  \n  \nWe can also check the `coordinateUncertaintyInMeters`, which gives us an indication of the error associated with a particular record. If we look at the names of the columns printed at the beginning of the script, you may notice that this column has been read as characters. We will change it to numbers before looking at the values in the column.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\n#Changing column from characters to numeric\ncaretta_obs <- caretta_obs %>% \n  mutate(coordinateUncertaintyInMeters = as.numeric(coordinateUncertaintyInMeters))\n\n#Checking uncertainty values for coordinates\ncaretta_obs %>% \n  distinct(coordinateUncertaintyInMeters)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 1\n  coordinateUncertaintyInMeters\n                          <dbl>\n1                          0.11\n2                     111319.  \n3                         NA   \n```\n:::\n:::\n\n  \nIt is worth noting that not all providers share a measurement of uncertainty, but we can use this whenever is available to apply some sort of quality control to our data.  \n  \nHere, we see that some observations have uncertainty of centimeters (0.11 m), but there are other observations with uncertainty over 100 km. For this example, we will remove these observations with large uncertainties.  \n  \n<<<<<<< HEAD\n## Quality control flags\n=======\n## Check quality control flags\n>>>>>>> e1113d9383b2e57473ce9195a510bd71774ecfda\nOBIS provides some quality control (QC) flags for each record that may help us identify observations of lower quality. For an explanation of OBIS flags, check [this repository](https://github.com/iobis/obis-qc).  \n  \nFirst, we will check the quality flags included in our results.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\ncaretta_obs %>% \n  distinct(flags)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 1\n  flags             \n  <chr>             \n1 NO_DEPTH          \n2 NO_DEPTH,ON_LAND  \n3 DEPTH_EXCEEDS_BATH\n4 <NA>              \n```\n:::\n:::\n\n  \nWe will now plot our dataset on a map and use the information in the `flags` column to color code the observations. This can help us decide whether we should include or exclude them from further analyses. \n  \n\n::: {.cell}\n\n```{.r .cell-code}\n#Getting a world base map\nworld <- ne_countries(scale = \"medium\", returnclass = \"sf\")\n\n#Starting a plot\nggplot()+\n  #Adding base layer (world map)\n  geom_sf(data = world)+\n  #Adding sea turtle observations\n  geom_point(data = caretta_obs, \n             #Using coordinates to plot and color based on value in flags column\n             aes(decimalLongitude, decimalLatitude, color = flags))+\n  #Constraining map to original bounding box\n  lims(x = c(st_bbox(extent_polygon)$xmin, st_bbox(extent_polygon)$xmax),\n       y = c(st_bbox(extent_polygon)$ymin, st_bbox(extent_polygon)$ymax))+\n  #Applying theme without background\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Get_seaturtle_data_files/figure-html/plot_qc-1.png){width=672}\n:::\n:::\n\n  \nFrom the plot above, we should consider removing at least some of the observations classified as `NO_DEPTH,ON_LAND`. This is because loggerhead sea turtles are not present inland. Instead, they are found in temperate and subtropical ocean waters and in sandy beaches.  \n  \nSome of these observations appear to be quite close to the shore, so they may have occurred in a sandy beach. We can check the proximity of the observation to the shore using the `shoredistance` column, which provides the distance to shore in meters.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaretta_obs %>% \n  filter(flags == \"NO_DEPTH,ON_LAND\") %>% \n  select(shoredistance) %>% \n  arrange(desc(shoredistance))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 25 × 1\n   shoredistance\n           <int>\n 1          -231\n 2          -394\n 3          -971\n 4         -1403\n 5         -3895\n 6         -5896\n 7         -8319\n 8         -8562\n 9        -17661\n10        -19763\n# … with 15 more rows\n```\n:::\n:::\n\n  \nThe inland observations are at least 231 meters away from the coast and up to 515 kilometers. For simplicity, we will remove all points flagged as `NO_DEPTH,ON_LAND`, but it is recommended that locations are looked more in depth and determine how likely it was that an individual was present at that location.  \n  \nWe can also check if any other observations have been reported in land. We will filter out the `NO_DEPTH,ON_LAND` flags and check for any negative values in the `shoredistance` column.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\ncaretta_obs %>% \n  filter(flags != \"NO_DEPTH,ON_LAND\" & shoredistance < 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 103\n# … with 103 variables: associatedReferences <chr>, basisOfRecord <chr>,\n#   bibliographicCitation <chr>, catalogNumber <chr>, collectionCode <chr>,\n#   coordinatePrecision <chr>, coordinateUncertaintyInMeters <dbl>,\n#   datasetID <chr>, datasetName <chr>, dateIdentified <chr>,\n#   decimalLatitude <dbl>, decimalLongitude <dbl>, eventDate <chr>,\n#   eventTime <chr>, family <chr>, footprintWKT <chr>, genus <chr>,\n#   geodeticDatum <chr>, georeferencedDate <chr>, …\n```\n:::\n:::\n\n  \nNo observations were returned, which is good news.  \n  \nAnother feature worth pointing out in our data is that some of the observations appear to be gridded as they are evenly spaced. This is confirmed by the `occurrenceRemarks` column, which states that some observations are: `Telemetry locations aggregated per species per 1-degree cell`. This is not ideal and you may need to consider if the inclusion of these data points are suitable for your project. In this example, we will remove them from our analysis.\n  \n## Problematic observations\nIn this step, we will remove observations with coordinate uncertainty over 100 km, any observations with the `NO_DEPTH,ON_LAND` flag, and any records that have been aggregated to a 1-degree cell.  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\n# caretta_obs %>% \n#   #Removing on land observations\n#   filter(flags != \"NO_DEPTH,ON_LAND\" | is.na(flags)) %>% \n#   #        | coordinateUncertaintyInMeters > 100000) %>% \n#   # filter(!str_detect(occurrenceRemarks, \"degree\"))\n```\n:::\n\n\n\n## Next steps\nNow that we've got explored the OBIS data we can finalize our dataset and import environmental data before running the SDM. For next steps, see `SDM Workflow` section.",
    "supporting": [
      "Get_seaturtle_data_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}