<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Marine SDMs - Obtaining presence data for loggerhead turtles from OBIS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../tutorial/02_Background_Data.html" rel="next">
<link href="../tutorial/00_Region.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tutorial/00_Roadmap.html">Background</a></li><li class="breadcrumb-item"><a href="../tutorial/01_Presence_Data.html">Presence data</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="https://oceanhackweek.org/_static/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://oceanhackweek.org/" title="OceanHackWeek" class="quarto-navigation-tool px-1" aria-label="OceanHackWeek"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/oceanhackweek" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tutorial/00_Roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/00_Region.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Region</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/01_Presence_Data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Presence data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/02_Background_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Absence data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/03_sdmpredictors-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Environmental data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/05_Link_env_to_pts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Link envionment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/05_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Types of models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/05_fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting models</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">SDM Steps</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/Steps_Region.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Save region objects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/Steps_occurences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Save presence data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/Steps_background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Save absence aata</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/Steps_occ_env.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Environmental Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/Steps_sdm_maxnet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fit with Maxnet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorial/Steps_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Full SDM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../SDM/Turtle_maxnet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Maxnet</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link active" data-scroll-target="#load-libraries">Load libraries</a></li>
  <li><a href="#load-the-region-data" id="toc-load-the-region-data" class="nav-link" data-scroll-target="#load-the-region-data">Load the region data</a></li>
  <li><a href="#get-observations" id="toc-get-observations" class="nav-link" data-scroll-target="#get-observations">Get Observations</a></li>
  <li><a href="#explore-obis-results" id="toc-explore-obis-results" class="nav-link" data-scroll-target="#explore-obis-results">Explore OBIS results</a></li>
  <li><a href="#quality-control-flags" id="toc-quality-control-flags" class="nav-link" data-scroll-target="#quality-control-flags">Quality control flags</a></li>
  <li><a href="#problematic-observations" id="toc-problematic-observations" class="nav-link" data-scroll-target="#problematic-observations">Problematic observations</a></li>
  <li><a href="#saving-clean-data" id="toc-saving-clean-data" class="nav-link" data-scroll-target="#saving-clean-data">Saving clean data</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/oceanhackweek/ohw23_proj_marinesdms/edit/main/tutorial/01_Presence_Data.Rmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/oceanhackweek/ohw23_proj_marinesdms/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Obtaining presence data for loggerhead turtles from OBIS</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this section, we will explore <a href="https://www.iucnredlist.org/species/3897/119333622">Loggerhead sea turtle (<em>Caretta caretta</em>)</a> data from 2000 until present from the <a href="https://obis.org/">Ocean Biodiversity Information System (OBIS)</a>. We will use the <code>robis</code> package to search the OBIS library and download relevant data. We will then check for quality control flags and remove problematic observations from the data (i.e., sea turtle observations on land).</p>
<section id="load-libraries" class="level2">
<h2 class="anchored" data-anchor-id="load-libraries">Load libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Dealing with spatial data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting base maps</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Access to OBIS</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(robis)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Data manipulation and visualisation</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-region-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-region-data">Load the region data</h2>
<p>We defined our region and bounding box in the <a href="tutorial/Region.html">Region</a> page.</p>
<p>Load the bounding box.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading bounding box for the area of interest</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>fil <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"region"</span>, <span class="st">"BoundingBox.shp"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>extent_polygon <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(fil)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Extract polygon geometry </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>pol_geometry <span class="ot">&lt;-</span> <span class="fu">st_as_text</span>(extent_polygon<span class="sc">$</span>geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="get-observations" class="level2">
<h2 class="anchored" data-anchor-id="get-observations">Get Observations</h2>
<p>We will use the <code>robis</code> package to find observations of Loggerhead sea turtles (<em>C. caretta</em>) published in OBIS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Search OBIS for loggerhead observations from 2000</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="ot">&lt;-</span> <span class="fu">occurrence</span>(<span class="st">"Caretta caretta"</span>, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">startdate =</span> <span class="fu">as.Date</span>(<span class="st">"2000-01-01"</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#Apply spatial constraint</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">geometry =</span> pol_geometry,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#Include absence records if available</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">absence =</span> <span class="st">"include"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Retrieved 5000 records of approximately 5269 (94%)
Retrieved 5269 records of
approximately 5269 (100%)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check structure of results</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(caretta_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,269
Columns: 103
$ associatedReferences          &lt;chr&gt; "[{\"crossref\":{\"citeinfo\":{\"origin\…
$ basisOfRecord                 &lt;chr&gt; "MachineObservation", "MachineObservatio…
$ bibliographicCitation         &lt;chr&gt; "[{\"crossref\":{\"citeinfo\":{\"origin\…
$ catalogNumber                 &lt;chr&gt; "1014_8853", "1014_9766", "1014_8861", "…
$ collectionCode                &lt;chr&gt; "1014", "1014", "1014", "1014", "1014", …
$ coordinatePrecision           &lt;chr&gt; "9.99999999999999955e-07", "9.9999999999…
$ coordinateUncertaintyInMeters &lt;chr&gt; "0.11", "0.11", "0.11", "0.11", "0.11", …
$ datasetID                     &lt;chr&gt; "1014", "1014", "1014", "1014", "1014", …
$ datasetName                   &lt;chr&gt; "IFREMER/Kélonia satellite tracked late …
$ dateIdentified                &lt;chr&gt; "2012-03-30T08:55:10", "2011-04-12T19:12…
$ decimalLatitude               &lt;dbl&gt; 9.14804, 6.40193, 9.21307, 15.39172, 15.…
$ decimalLongitude              &lt;dbl&gt; 50.69448, 59.87883, 50.82211, 55.71303, …
$ eventDate                     &lt;chr&gt; "2012-03-30T08:55:10", "2011-04-12T19:12…
$ eventTime                     &lt;chr&gt; "05:55:10Z", "15:12:41Z", "23:43:31Z", "…
$ family                        &lt;chr&gt; "Cheloniidae", "Cheloniidae", "Cheloniid…
$ footprintWKT                  &lt;chr&gt; "POINT(50.69448 9.14804)", "POINT(59.878…
$ genus                         &lt;chr&gt; "Caretta", "Caretta", "Caretta", "Carett…
$ geodeticDatum                 &lt;chr&gt; "EPSG:4326 WGS84", "EPSG:4326 WGS84", "E…
$ georeferencedDate             &lt;chr&gt; "2012-03-30T08:55:10", "2011-04-12T19:12…
$ identificationRemarks         &lt;chr&gt; "Identification Type:Telemetry", "Identi…
$ individualCount               &lt;chr&gt; "1", "1", "1", "1", "1", "1", "1", "1", …
$ institutionCode               &lt;chr&gt; "IFREMER and Kélonia", "IFREMER and Kélo…
$ kingdom                       &lt;chr&gt; "Animalia", "Animalia", "Animalia", "Ani…
$ license                       &lt;chr&gt; "http://creativecommons.org/licenses/by-…
$ lifeStage                     &lt;chr&gt; "Juvenile", "Juvenile", "Juvenile", "Juv…
$ modified                      &lt;chr&gt; "2013-10-25 13:35:20", "2013-10-25 13:35…
$ nomenclaturalCode             &lt;chr&gt; "WoRMS LSID", "WoRMS LSID", "WoRMS LSID"…
$ occurrenceID                  &lt;chr&gt; "1014_8853", "1014_9766", "1014_8861", "…
$ occurrenceRemarks             &lt;chr&gt; "Telemetry", "Telemetry", "Telemetry", "…
$ occurrenceStatus              &lt;chr&gt; "present", "present", "present", "presen…
$ order                         &lt;chr&gt; "Testudines", "Testudines", "Testudines"…
$ organismID                    &lt;chr&gt; "57684", "66818", "57684", "66839", "668…
$ organismRemarks               &lt;chr&gt; "Tagged animal. organismID may refer to …
$ ownerInstitutionCode          &lt;chr&gt; "IFREMER and Kélonia", "IFREMER and Kélo…
$ phylum                        &lt;chr&gt; "Chordata", "Chordata", "Chordata", "Cho…
$ recordNumber                  &lt;chr&gt; "1014_8853", "1014_9766", "1014_8861", "…
$ scientificName                &lt;chr&gt; "Caretta caretta", "Caretta caretta", "C…
$ scientificNameAuthorship      &lt;chr&gt; "(Linnaeus, 1758)", "(Linnaeus, 1758)", …
$ scientificNameID              &lt;chr&gt; "urn:lsid:marinespecies.org:taxname:1372…
$ specificEpithet               &lt;chr&gt; "caretta", "caretta", "caretta", "carett…
$ taxonRank                     &lt;chr&gt; "Species", "Species", "Species", "Specie…
$ taxonRemarks                  &lt;chr&gt; "Taxon recorded as \"Caretta caretta\" b…
$ taxonomicStatus               &lt;chr&gt; "valid", "valid", "valid", "valid", "val…
$ type                          &lt;chr&gt; "Event", "Event", "Event", "Event", "Eve…
$ verbatimEventDate             &lt;chr&gt; "2012-03-30 08:55:10", "2011-04-12 19:12…
$ vernacularName                &lt;chr&gt; "Loggerhead Sea Turtle", "Loggerhead Sea…
$ waterBody                     &lt;chr&gt; "Reunion Island,Oman,South-Africa", "Reu…
$ id                            &lt;chr&gt; "000341f8-f206-4120-bc73-432a0c729d7a", …
$ dataset_id                    &lt;chr&gt; "7687b242-05b7-48d7-a316-ba6dc34e72b5", …
$ node_id                       &lt;chr&gt; "573654c1-4ce7-4ea2-b2f1-e4d42f8f9c31", …
$ date_start                    &lt;dbl&gt; 1.333066e+12, 1.302566e+12, 1.333152e+12…
$ date_mid                      &lt;dbl&gt; 1.333066e+12, 1.302566e+12, 1.333152e+12…
$ date_end                      &lt;dbl&gt; 1.333066e+12, 1.302566e+12, 1.333152e+12…
$ date_year                     &lt;int&gt; 2012, 2011, 2012, 2011, 2011, 2011, 2011…
$ dropped                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
$ absence                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
$ marine                        &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
$ subphylum                     &lt;chr&gt; "Vertebrata", "Vertebrata", "Vertebrata"…
$ infraphylum                   &lt;chr&gt; "Gnathostomata", "Gnathostomata", "Gnath…
$ megaclass                     &lt;chr&gt; "Tetrapoda", "Tetrapoda", "Tetrapoda", "…
$ superclass                    &lt;chr&gt; "Reptilia", "Reptilia", "Reptilia", "Rep…
$ suborder                      &lt;chr&gt; "Cryptodira", "Cryptodira", "Cryptodira"…
$ superfamily                   &lt;chr&gt; "Chelonioidea", "Chelonioidea", "Cheloni…
$ species                       &lt;chr&gt; "Caretta caretta", "Caretta caretta", "C…
$ kingdomid                     &lt;int&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
$ phylumid                      &lt;int&gt; 1821, 1821, 1821, 1821, 1821, 1821, 1821…
$ subphylumid                   &lt;int&gt; 146419, 146419, 146419, 146419, 146419, …
$ infraphylumid                 &lt;int&gt; 1828, 1828, 1828, 1828, 1828, 1828, 1828…
$ megaclassid                   &lt;int&gt; 1831, 1831, 1831, 1831, 1831, 1831, 1831…
$ superclassid                  &lt;int&gt; 1838, 1838, 1838, 1838, 1838, 1838, 1838…
$ orderid                       &lt;int&gt; 2689, 2689, 2689, 2689, 2689, 2689, 2689…
$ suborderid                    &lt;int&gt; 148741, 148741, 148741, 148741, 148741, …
$ superfamilyid                 &lt;int&gt; 987094, 987094, 987094, 987094, 987094, …
$ familyid                      &lt;int&gt; 136999, 136999, 136999, 136999, 136999, …
$ genusid                       &lt;int&gt; 137066, 137066, 137066, 137066, 137066, …
$ speciesid                     &lt;int&gt; 137205, 137205, 137205, 137205, 137205, …
$ aphiaID                       &lt;int&gt; 137205, 137205, 137205, 137205, 137205, …
$ originalScientificName        &lt;chr&gt; "Caretta caretta", "Caretta caretta", "C…
$ category                      &lt;chr&gt; "VU", "VU", "VU", "VU", "VU", "VU", "VU"…
$ flags                         &lt;chr&gt; "NO_DEPTH", "NO_DEPTH", "NO_DEPTH", "NO_…
$ bathymetry                    &lt;int&gt; 35, 3051, 136, 2784, 2453, 2736, 2880, 2…
$ shoredistance                 &lt;int&gt; 4680, 899682, 12208, 193567, 143853, 100…
$ sst                           &lt;dbl&gt; 26.21, 28.67, 26.21, 27.00, 26.92, 26.92…
$ sss                           &lt;dbl&gt; 35.63, 35.74, 35.65, 36.09, 36.09, 36.10…
$ dynamicProperties             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sex                           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ continent                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ country                       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ day                           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ georeferenceRemarks           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ locality                      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ maximumDepthInMeters          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ maximumElevationInMeters      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ minimumDepthInMeters          &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ minimumElevationInMeters      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ month                         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ recordedBy                    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ references                    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ samplingProtocol              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ year                          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ depth                         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ superdomain                   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ superdomainid                 &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …</code></pre>
</div>
</div>
</section>
<section id="explore-obis-results" class="level2">
<h2 class="anchored" data-anchor-id="explore-obis-results">Explore OBIS results</h2>
<p>Our search produced 5269 results for the area of our interest. However, before we continue to use this data as input for our species distribution models, we must clean it first to ensure we have a good quality dataset.</p>
<p>In this section, we will explore the results of our OBIS search so we can design a data cleaning workflow. We will check the content of some of the columns in our data frame.</p>
<p>You may want to refer to the <a href="https://manual.obis.org/darwin_core.html">OBIS manual</a> and the OBIS webpage about <a href="https://obis.org/data/access/">Data Access</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking values in basis of record column</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(basisOfRecord)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 1
  basisOfRecord     
  &lt;chr&gt;             
1 MachineObservation
2 Occurrence        </code></pre>
</div>
</div>
<p>In this context, <code>MachineObservation</code> refers to records obtained with satellite tags. While <code>Occurrence</code> refers to records obtained by human observers on the field. These two datasets cannot be treated in the same way as <code>MachineObservation</code> records are not independent as they record the movements of a single individual.</p>
<p>We can also check whether or not absence data is available for the loggerhead se a turtles in our area of interest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(absence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  absence
  &lt;lgl&gt;  
1 FALSE  </code></pre>
</div>
</div>
<p>We only have presence data available, which is an important factor to consider when designing our species distribution model workflow.</p>
<p>We can also check the <code>coordinateUncertaintyInMeters</code>, which gives us an indication of the error associated with a particular record. If we look at the names of the columns printed at the beginning of the script, you may notice that this column has been read as characters. We will change it to numbers before looking at the values in the column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Changing column from characters to numeric</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="ot">&lt;-</span> caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">coordinateUncertaintyInMeters =</span> <span class="fu">as.numeric</span>(coordinateUncertaintyInMeters))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking uncertainty values for coordinates</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(coordinateUncertaintyInMeters)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  coordinateUncertaintyInMeters
                          &lt;dbl&gt;
1                          0.11
2                     111319.  
3                         NA   </code></pre>
</div>
</div>
<p>It is worth noting that not all providers share a measurement of uncertainty, but we can use this whenever is available to apply some sort of quality control to our data.</p>
<p>Here, we see that some observations have uncertainty of centimeters (0.11 m), but there are other observations with uncertainty over 100 km. For this example, we will remove these observations with large uncertainties.</p>
</section>
<section id="quality-control-flags" class="level2">
<h2 class="anchored" data-anchor-id="quality-control-flags">Quality control flags</h2>
<p>OBIS provides some quality control (QC) flags for each record that may help us identify observations of lower quality. For an explanation of OBIS flags, check <a href="https://github.com/iobis/obis-qc">this repository</a>.</p>
<p>First, we will check the quality flags included in our results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(flags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 1
  flags             
  &lt;chr&gt;             
1 NO_DEPTH          
2 NO_DEPTH,ON_LAND  
3 DEPTH_EXCEEDS_BATH
4 &lt;NA&gt;              </code></pre>
</div>
</div>
<p>We will now plot our dataset on a map and use the information in the <code>flags</code> column to color code the observations. This can help us decide whether we should include or exclude them from further analyses.</p>
<p>First we will load the region map that was saved in the <a href="tutorial/00_Region.Rmd">Region page</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fil <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"region"</span>, <span class="st">"region_map_label.rda"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(fil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>region_map_label <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> caretta_obs, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>             <span class="co">#Using coordinates to plot and color based on value in flags column</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(decimalLongitude, decimalLatitude, <span class="at">color =</span> flags))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale on map varies by more than 10%, scale bar may be inaccurate</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 231 rows containing missing values (`geom_text()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="01_Presence_Data_files/figure-html/plot_qc-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the plot above, we should consider removing at least some of the observations classified as <code>NO_DEPTH,ON_LAND</code>. This is because loggerhead sea turtles are not present inland. Instead, they are found in temperate and subtropical ocean waters and in sandy beaches.</p>
<p>Some of these observations appear to be quite close to the shore, so they may have occurred in a sandy beach. We can check the proximity of the observation to the shore using the <code>shoredistance</code> column, which provides the distance to shore in meters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(flags <span class="sc">==</span> <span class="st">"NO_DEPTH,ON_LAND"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(shoredistance) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(shoredistance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 1
   shoredistance
           &lt;int&gt;
 1          -231
 2          -394
 3          -971
 4         -1403
 5         -3895
 6         -5896
 7         -8319
 8         -8562
 9        -17661
10        -19763
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>The inland observations are at least 231 meters away from the coast and up to 515 kilometers. For simplicity, we will remove all points flagged as <code>NO_DEPTH,ON_LAND</code>, but it is recommended that locations are looked more in depth and determine how likely it was that an individual was present at that location.</p>
<p>We can also check if any other observations have been reported in land. We will filter out the <code>NO_DEPTH,ON_LAND</code> flags and check for any negative values in the <code>shoredistance</code> column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(flags <span class="sc">!=</span> <span class="st">"NO_DEPTH,ON_LAND"</span> <span class="sc">&amp;</span> shoredistance <span class="sc">&lt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 103
# ℹ 103 variables: associatedReferences &lt;chr&gt;, basisOfRecord &lt;chr&gt;,
#   bibliographicCitation &lt;chr&gt;, catalogNumber &lt;chr&gt;, collectionCode &lt;chr&gt;,
#   coordinatePrecision &lt;chr&gt;, coordinateUncertaintyInMeters &lt;dbl&gt;,
#   datasetID &lt;chr&gt;, datasetName &lt;chr&gt;, dateIdentified &lt;chr&gt;,
#   decimalLatitude &lt;dbl&gt;, decimalLongitude &lt;dbl&gt;, eventDate &lt;chr&gt;,
#   eventTime &lt;chr&gt;, family &lt;chr&gt;, footprintWKT &lt;chr&gt;, genus &lt;chr&gt;,
#   geodeticDatum &lt;chr&gt;, georeferencedDate &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>No observations were returned, which is good news.</p>
<p>Another feature worth pointing out in our data is that some of the observations appear to be gridded as they are evenly spaced. This is confirmed by the <code>occurrenceRemarks</code> column, which states that some observations are: <code>Telemetry locations aggregated per species per 1-degree cell</code>. This is not ideal and you may need to consider if the inclusion of these data points are suitable for your project. In this example, we will remove them from our analysis.</p>
</section>
<section id="problematic-observations" class="level2">
<h2 class="anchored" data-anchor-id="problematic-observations">Problematic observations</h2>
<p>In this step, we will remove observations with coordinate uncertainty over 100 km, any observations with the <code>NO_DEPTH,ON_LAND</code> flag, and any records that have been aggregated to a 1-degree cell.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>caretta_obs <span class="ot">&lt;-</span> caretta_obs <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Removing on land observations</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(flags <span class="sc">!=</span> <span class="st">"NO_DEPTH,ON_LAND"</span> <span class="sc">|</span> <span class="fu">is.na</span>(flags)) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Removing observations with uncertainty over 100 km</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(coordinateUncertaintyInMeters <span class="sc">&lt;=</span> <span class="dv">100000</span> <span class="sc">|</span> <span class="fu">is.na</span>(coordinateUncertaintyInMeters)) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Removing records aggregated to 1 degree </span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(occurrenceRemarks, <span class="st">"degree"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="saving-clean-data" class="level2">
<h2 class="anchored" data-anchor-id="saving-clean-data">Saving clean data</h2>
<p>Now that we have removed the problematic observations, we can save the new dataset into our local machine. We will save this under the <code>data</code> folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fil <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"raw-bio"</span>, <span class="st">"loggerhead-robis.csv"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(caretta_obs, fil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../tutorial/00_Region.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Region</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../tutorial/02_Background_Data.html" class="pagination-link">
        <span class="nav-page-text">Absence data</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">OceanHackWeek Tutorial</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>